#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

#  updates the package lists for available software packages.
apt-get update
# installs the Nginx web server.
apt-get install -y nginx

sudo sed -i 's|return 200 '\''Hello World!'\'';|try_files $uri $uri/ =404;|g' /etc/nginx/sites-enabled/default

# Restarts the Nginx service to apply the configuration changes.
service nginx restart
