#!/usr/bin/env bash
#Install nginx web server
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo touch /var/www/html/index.html
sudo chmod 666 /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
service nginx restart
