#!/usr/bin/env bash
# Configures a new ubuntu machine by installing nginx

sudo apt-get update && sudo apt-get install nginx -y

# starting nginx service
sudo service nginx start

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Use sed to modify the default configuration
sed -i "/root \;/a\
    location / {\
        root /var/www/html;\
        index index.nginx-debian.html index.html index.htm;\
        \
        # Serve 'Hello World!' for the root path\
        if (\$uri = '/') {\
            return 200 'Hello World!';\
        }\
        \
        # Redirect '/redirect_me' to google.com with 301 status\
        location /redirect_me {\
            return 301 https://google.com;\
        }\
    }" /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart
