#!/usr/bin/env bash
#Install nginx web server and Redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {rewrite ^/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
sudo service nginx start
