#!/usr/bin/env bash
# Configures a new ubuntu machine by installing nginx

sudo apt-get update && sudo apt-get install nginx -y

# starting nginx service
sudo service nginx start

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Use sed to modify the default configuration
sed -i '
  s/listen 80 default_server;/listen 80; server_name localhost;/g' /etc/nginx/sites-available/default
  /root \;/a location / { \n  root /var/www/html; \n  index index.html index.htm; \n  \n  # Serve "Hello World!" for the root path \n  if ($uri = "/") { \n    return 200 "Hello World!"; \n  } \n  \n  # Redirect "/redirect_me" to google.com with 301 status \n  location /redirect_me { \n    return 301 https://google.com; \n  } \n}' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart
