#!/usr/bin/env bash
#Install nginx web server and Redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo touch /var/www/html/index.html
sudo chmod 766 /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
#sudo chown -R "$USER":"$USER" /var/www/html
#sudo chown -R 744 /var/www
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {rewrite ^/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' /etc/nginx/sites-available/default
sudo sed -i 's/=404/@404/g' /etc/nginx/sites-available/default
sudo service nginx restart
