#!/usr/bin/env bash
#Install nginx web server and Redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo touch /var/www/html/index.html
sudo chmod 666 /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {\n\t\trewrite ^/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo touch /var/www/html/404.html
sudo chmod 666 /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/^}$/i \ \n\terror_page 404 /404.html;\n\n\tlocation /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
