#!/bin/bash
# configure Nginx to be running as the nginx user

# stop nginx running
sudo service nginx stop

# Set the user to run Nginx as master process
sed -i 's/#user\s*.*;/user nginx;/' /etc/nginx/nginx.conf

# Configure /etc/nginx/sites-enabled/default to bind Nginx to port 8080
sed -i 's/listen\s*.*default_server;/listen 8080 default_server;/' /etc/nginx/sites-enabled/default

# Give /etc/nginx/nginx.conf the permission 644
chmod 644 /etc/nginx/nginx.conf

# check for service running on port 8080
SERVICE=$(lsof -ti :8080)

if [ -n "$SERVICE" ]; then
    echo "Service running on port 8080, PID: $SERVICE"
    # Kill the service running on port 8080
    kill "$SERVICE"
    echo "Service killed."
else
    echo "No service found running on port 8080."
fi

# restart nginx
sudo -u nginx service nginx restart
